/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Kevin Rivas
 */
public class Bienvenido extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenido
     */
    public Bienvenido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 245, 213));
        setPreferredSize(new java.awt.Dimension(1145, 717));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/MicrosoftTeams-image.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 127, -1, -1));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(133, 175, 75));
        jLabel2.setText("Bolsa de trabajo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 117, 42));
        jLabel3.setText("Bienvenido");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 25, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 117, 42));
        jLabel4.setText("sacculum");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
